# Generated by Django 2.1.5 on 2020-05-12 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=60)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
            ],
        ),
    ]
